name: Merge main into production

on:
  pull_request:
    types:
      - closed

jobs:
  production:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    name: Create PR update main to production
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: production
          pr_title: '[Automated] PR #${{ github.event.pull_request.number }}: Merge ${{ github.ref_name }} into production'
          pr_body: 'Automated Pull Request'
